"""Render the before/after HTML report.

Standalone HTML — pure CSS bar charts, no JS, no external network requests
at render time. Open the file directly in a browser; no server needed.

The summary narrative is generated by:
  - dry-run: a template string with f-string substitutions
  - live:    Claude Sonnet 4.6 for one short paragraph (~3 sentences)
"""

from __future__ import annotations

import os
import webbrowser
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd
from jinja2 import Environment, FileSystemLoader, select_autoescape

from ..audit import AuditResult
from ..enrichment.confidence_tracker import ConfidenceTracker


@dataclass
class StageTiming:
    stage: str
    seconds: float


@dataclass
class ReportInputs:
    """Everything the template needs in one bag."""
    seed_csv_path: str
    mode: str
    audit_before: AuditResult
    audit_after: AuditResult
    n_accounts_before: int
    n_accounts_after: int
    n_contacts_before: int
    n_llm_resolved: int
    merge_plan: list      # list of MergePlanEntry
    tracker: ConfidenceTracker
    stage_timing: list[StageTiming] = field(default_factory=list)


# --- narrative ---------------------------------------------------------------

_DRY_RUN_TEMPLATE = (
    "Audited <strong>{n_before} accounts × {n_contacts} contacts</strong>. "
    "Caught <strong>{n_dups} duplicate pairs</strong> ({n_high_dups} auto-merged at rapidfuzz score 90+, "
    "{n_llm} resolved by the LLM tie-breaker in the 70–89 gray zone). "
    "After merge: <strong>{n_after} canonical accounts</strong>. "
    "Enrichment waterfall filled <strong>{n_fills} blank fields</strong> across {n_field_kinds} field types "
    "(industry, employees, revenue, country) — Apollo covered {apollo} records, "
    "mock_clearbit covered {clearbit}, Claude inferred the rest. "
    "Critical issues dropped from {high_before} → {high_after}."
)


def _build_narrative_dry_run(inputs: ReportInputs) -> str:
    by_source = inputs.tracker.by_source()
    dups = inputs.audit_before.counts_by_type.get("duplicate_candidate", 0)
    high_dups = sum(
        1 for i in inputs.audit_before.issues
        if i.issue_type == "duplicate_candidate" and i.severity == "high" and i.record_type == "account"
    )
    return _DRY_RUN_TEMPLATE.format(
        n_before=inputs.n_accounts_before,
        n_contacts=inputs.n_contacts_before,
        n_dups=dups,
        n_high_dups=high_dups,
        n_llm=inputs.n_llm_resolved,
        n_after=inputs.n_accounts_after,
        n_fills=len(inputs.tracker),
        n_field_kinds=len(inputs.tracker.by_field()),
        apollo=by_source.get("apollo", 0),
        clearbit=by_source.get("mock_clearbit", 0),
        high_before=inputs.audit_before.counts_by_severity.get("high", 0),
        high_after=inputs.audit_after.counts_by_severity.get("high", 0),
    )


def _build_narrative_live(inputs: ReportInputs) -> str:
    """One short paragraph from Sonnet 4.6 — falls back to dry-run text on error."""
    try:
        from anthropic import Anthropic
    except ImportError:
        return _build_narrative_dry_run(inputs)
    if not os.getenv("ANTHROPIC_API_KEY"):
        return _build_narrative_dry_run(inputs)

    facts = {
        "accounts_before": inputs.n_accounts_before,
        "accounts_after": inputs.n_accounts_after,
        "contacts_before": inputs.n_contacts_before,
        "issue_counts_before": inputs.audit_before.counts_by_type,
        "issue_counts_after": inputs.audit_after.counts_by_type,
        "severity_before": inputs.audit_before.counts_by_severity,
        "severity_after": inputs.audit_after.counts_by_severity,
        "fields_enriched": len(inputs.tracker),
        "fields_by_source": inputs.tracker.by_source(),
        "llm_decisions_for_dupes": inputs.n_llm_resolved,
        "merge_groups": len(inputs.merge_plan),
    }
    prompt = (
        "You are writing a 3-sentence summary for a Revenue Operations leader looking at a "
        "CRM hygiene before/after report. Tone: dry, factual, numerate. No marketing words. "
        "Lead with the biggest movement. Use exact numbers from the JSON. Wrap any number you "
        "highlight in <strong>...</strong> tags (HTML-safe). Max 3 sentences.\n\n"
        f"Facts:\n{facts}"
    )
    try:
        client = Anthropic()
        msg = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=300,
            messages=[{"role": "user", "content": prompt}],
        )
        return msg.content[0].text.strip()
    except Exception:
        return _build_narrative_dry_run(inputs)


# --- table assembly ----------------------------------------------------------


def _issue_table(before: AuditResult, after: AuditResult) -> list[dict]:
    keys = sorted(set(before.counts_by_type) | set(after.counts_by_type))
    rows = []
    for k in keys:
        b = before.counts_by_type.get(k, 0)
        a = after.counts_by_type.get(k, 0)
        rows.append({"type": k, "before": b, "after": a, "delta": max(0, b - a)})
    rows.sort(key=lambda r: -r["delta"])
    return rows


_REPORTED_FIELDS = ["industry", "annual_revenue", "employee_count", "country", "phone", "state"]


def _fill_rate_rows(before: AuditResult, after: AuditResult) -> list[dict]:
    rows = []
    for f in _REPORTED_FIELDS:
        b = before.account_fill_rates.get(f, 0.0) * 100
        a = after.account_fill_rates.get(f, 0.0) * 100
        rows.append({"field": f, "before_pct": round(b, 1), "after_pct": round(a, 1)})
    return rows


def _enrichment_source_rows(tracker: ConfidenceTracker) -> list[dict]:
    by_src = tracker.by_source()
    if not by_src:
        return []
    mx = max(by_src.values())
    colors = {"apollo": "var(--accent)", "mock_clearbit": "var(--amber)", "claude_websearch": "var(--green)"}
    return [
        {
            "source": src,
            "count": cnt,
            "pct_of_max": round(100 * cnt / mx, 1),
            "color": colors.get(src, "var(--accent)"),
        }
        for src, cnt in sorted(by_src.items(), key=lambda kv: -kv[1])
    ]


def _top_merge_groups(merge_plan, accounts_before: pd.DataFrame, k: int = 5) -> list[dict]:
    """Pick representative merge groups for the report.

    Sort order: by canonical_id ascending. The hero dupes (Acme, Globex,
    Initech) are seeded at the lowest IDs, so they naturally lead — keeps
    the Loom storyline tight ('watch the Acme variants disappear')."""
    by_id = {str(r["id"]): r.to_dict() for _, r in accounts_before.iterrows()}
    # Only show groups with >= 2 variants (more dramatic) — filter then sort.
    plan_filtered = [p for p in merge_plan if len(p.merged_ids) >= 2]
    plan_sorted = sorted(plan_filtered, key=lambda p: p.canonical_id)
    # Fall back to size-sorted if we have <k multi-variant groups.
    if len(plan_sorted) < k:
        rest = sorted(
            [p for p in merge_plan if p not in plan_sorted],
            key=lambda p: -len(p.merged_ids),
        )
        plan_sorted = plan_sorted + rest

    out = []
    for p in plan_sorted[:k]:
        canonical = by_id.get(p.canonical_id, {})
        variants = [by_id.get(mid, {}).get("name", mid) for mid in p.merged_ids]
        out.append({
            "canonical_name": canonical.get("name", p.canonical_id),
            "variants": variants,
            "confidence": p.confidence,
            "reasoning": (p.reasoning[:200] + "…") if len(p.reasoning) > 200 else p.reasoning,
        })
    return out


def _stage_timing_rows(timings: list[StageTiming]) -> list[dict]:
    if not timings:
        return []
    mx = max(t.seconds for t in timings) or 1
    return [
        {"stage": t.stage, "seconds": round(t.seconds, 2), "pct": round(100 * t.seconds / mx, 1)}
        for t in timings
    ]


def render_report(
    inputs: ReportInputs,
    accounts_before: pd.DataFrame,
    out_path: Path,
    *,
    live: bool = False,
    open_browser: bool = True,
) -> Path:
    """Render the HTML and (optionally) open it. Returns the file path."""
    template_dir = Path(__file__).parent / "templates"
    env = Environment(
        loader=FileSystemLoader(template_dir),
        autoescape=select_autoescape(["html"]),
    )
    template = env.get_template("before_after.html")

    narrative = _build_narrative_live(inputs) if live else _build_narrative_dry_run(inputs)
    issue_table = _issue_table(inputs.audit_before, inputs.audit_after)
    total_before = sum(r["before"] for r in issue_table)
    total_after = sum(r["after"] for r in issue_table)
    timing_rows = _stage_timing_rows(inputs.stage_timing)

    ctx: dict[str, Any] = {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "mode": inputs.mode,
        "seed_csv_path": inputs.seed_csv_path,
        "n_accounts_before": inputs.n_accounts_before,
        "n_accounts_after": inputs.n_accounts_after,
        "n_contacts_before": inputs.n_contacts_before,
        "n_accounts_merged_away": inputs.n_accounts_before - inputs.n_accounts_after,
        "n_dup_pairs": inputs.audit_before.counts_by_type.get("duplicate_candidate", 0),
        "n_high_severity_dups": sum(
            1 for i in inputs.audit_before.issues
            if i.issue_type == "duplicate_candidate" and i.severity == "high" and i.record_type == "account"
        ),
        "n_llm_resolved": inputs.n_llm_resolved,
        "n_fields_enriched": len(inputs.tracker),
        "n_distinct_fields": len(inputs.tracker.by_field()),
        "n_high_before": inputs.audit_before.counts_by_severity.get("high", 0),
        "n_high_after": inputs.audit_after.counts_by_severity.get("high", 0),
        "issue_table": issue_table,
        "total_before": total_before,
        "total_after": total_after,
        "fill_rate_rows": _fill_rate_rows(inputs.audit_before, inputs.audit_after),
        "top_merge_groups": _top_merge_groups(inputs.merge_plan, accounts_before),
        "enrichment_source_rows": _enrichment_source_rows(inputs.tracker),
        "confidence_breakdown": ", ".join(f"{k}: {v}" for k, v in inputs.tracker.by_confidence().items()) or "(none)",
        "narrative_paragraph": narrative,
        "stage_timing": timing_rows,
        "total_seconds": round(sum(t.seconds for t in inputs.stage_timing), 2),
    }

    html = template.render(**ctx)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html)

    if open_browser:
        try:
            webbrowser.open(out_path.resolve().as_uri())
        except Exception:
            pass
    return out_path
